
export const data = [
    {
      id: '2',
      title: 'Cell 4 Less Limited',
      description: '',
      street: 'Kiosk #20, Aboutique Mall, 8 - 10 Frederick Street',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6504667',
      lng: '-61.5095972',
      phone: '625-8627',
      email: 'c4l.aboutique@gmail.com',
      website: 'www.cell4lesslimited.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 04:00 PM"],"tue":["09:00 AM - 04:00 PM"],"wed":["09:00 AM - 04:00 PM"],"thu":["09:00 AM - 04:00 PM"],"fri":["09:00 AM - 04:00 PM"],"sat":["09:00 AM - 04:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '3',
      title: 'Cell 4 Less Limited',
      description: '',
      street: 'C1, K05, Lower Level, Trincity Mall, Trincity Central Road',
      city: 'Trincity',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6269678',
      lng: '-61.3541186',
      phone: '640-8315',
      email: 'trincitymall@cell4lesslimited.com',
      website: 'www.cell4lesslimited.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 04:00 PM"],"tue":["10:00 AM - 04:00 PM"],"wed":["10:00 AM - 04:00 PM"],"thu":["10:00 AM - 04:00 PM"],"fri":["10:00 AM - 04:00 PM"],"sat":["10:00 AM - 04:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '4',
      title: 'Cell 4 Less Limited',
      description: '',
      street: 'Bldg J, Shop #5 & 6, City Of Grand Bazaar',
      city: 'Valsayn',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '47.9252568',
      lng: '-97.0328547',
      phone: '662-7421',
      email: 'grandbazaar@cell4lesslimited.com',
      website: 'www.cell4lesslimited.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 04:00 PM"],"tue":["10:00 AM - 04:00 PM"],"wed":["10:00 AM - 04:00 PM"],"thu":["10:00 AM - 04:00 PM"],"fri":["10:00 AM - 04:00 PM"],"sat":["10:00 AM - 04:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '1',
      title: 'Cell 4 Less Limited',
      description: '',
      street: 'Shop U35, Centre City Mall',
      city: 'Chaguanas',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.5164155',
      lng: '-61.410354',
      phone: '665-9072',
      email: 'c4l.chaguanas@gmail.com',
      website: 'www.cell4lesslimited.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 04:00 PM"],"tue":["09:00 AM - 04:00 PM"],"wed":["09:00 AM - 04:00 PM"],"thu":["09:00 AM - 04:00 PM"],"fri":["09:00 AM - 04:00 PM"],"sat":["09:00 AM - 04:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '11',
      title: 'Cell Serve Limited',
      description: '',
      street: 'Shop #11, Bradford City Mall, Henry Street',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6509973',
      lng: '-61.5084014',
      phone: '624-3827',
      email: 'cellservepos@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '16',
      title: 'Cell Serve Limited',
      description: '',
      street:
        'Block B, Shop B325, C3 Centre, Sir Solomon Hochoy Highway, Corinth',
      city: 'San Fernando',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.2746032',
      lng: '-61.4384591',
      phone: '652-5269',
      email: 'cellservec3@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '15',
      title: 'Cell Serve Limited',
      description: '',
      street: '219 Southern Main Road',
      city: 'Couva',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.4378529',
      lng: '-61.4528933',
      phone: '679-5961',
      email: 'cellservecouva@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 05:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '14',
      title: 'Cell Serve Limited',
      description: '',
      street: '#349 Brierley Street',
      city: 'Sangre Grande',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.5865694',
      lng: '-61.1305388',
      phone: '668-1573',
      email: 'cellservegrande@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 05:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '13',
      title: 'Cell Serve Limited',
      description: '',
      street: '#96A, A & S Mall, High Street',
      city: 'San Fernando',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.3015828',
      lng: '-61.4490453',
      phone: '652-6127',
      email: 'cellservesando@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 02:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '12',
      title: 'Cell Serve Limited',
      description: '',
      street: 'Bmobile Kiosk109 South, Ground Floor, Westmall',
      city: 'Westmoorings',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6772942',
      lng: '-61.5617847',
      phone: '632-2678',
      email: 'cellservewestmall@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '10',
      title: 'Cell Serve Limited',
      description: '',
      street: '#80 Cor. Eastern Main Road & Henry Street',
      city: 'Arouca',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.635511',
      lng: '-61.3439216',
      phone: '692-2263',
      email: 'cellservearouca@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '9',
      title: 'Cell Serve Limited',
      description: '',
      street: 'Shop P1, Arima Shopping Mall, 22 Green Street',
      city: 'Arima',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6407983',
      lng: '-61.2818152',
      phone: '667-0589',
      email: 'cellservearima@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '8',
      title: 'Cell Serve Limited',
      description: '',
      street: 'Maritime Centre (opp Food Court)',
      city: 'Barataria',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6476342',
      lng: '-61.4680443',
      phone: '638-8117',
      email: 'cellservemaritime@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '7',
      title: 'Cell Serve Limited',
      description: '',
      street: 'Block F1.K02 Ground Floor Kiosk, Trincity Mall, Southside',
      city: 'Trincity',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6339975',
      lng: '-61.3545607',
      phone: '640-0941',
      email: 'cellservetrincity@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '6',
      title: 'Cell Serve Limited',
      description: '',
      street: 'City Centre Mall, 1343 SS Erin Rd',
      city: 'Penal',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.1693276',
      lng: '-61.4578018',
      phone: '647-0393',
      email: 'cellservepenal@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '5',
      title: 'Cell Serve Limited',
      description: '',
      street: 'Unit 4, #43 Eastern Main Rd',
      city: 'Curepe',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6377843',
      lng: '-61.4056127',
      phone: '662-0849',
      email: 'cellservecurepe@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 05:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '65',
      title: 'Cellmaster Limited',
      description: '',
      street: 'Units 7, 8 & 9, Nicholas Towers, 63-65 Independence Square',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'Trinidad and Tobago',
      lat: '10.649215041644846',
      lng: '-61.51092610922242',
      phone: '',
      email: '',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '1',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["08:00 AM - 12:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: null,
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '25',
      title: 'Cellmaster Limited',
      description: '',
      street: 'Unit U29 Upper Level, Gulf City Shopping Mall',
      city: 'La Romain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '28.2937227',
      lng: '-82.7125372',
      phone: '653-7702',
      email: 'bmobile_gulfes@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 07:00 PM"],"tue":["10:00 AM - 07:00 PM"],"wed":["10:00 AM - 07:00 PM"],"thu":["10:00 AM - 07:00 PM"],"fri":["10:00 AM - 07:00 PM"],"sat":["10:00 AM - 07:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '24',
      title: 'Cellmaster Limited',
      description: '',
      street: 'Shop 181 Ground Floor East, The Falls at Westmall',
      city: 'Westmoorings',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6781651',
      lng: '-61.5536603',
      phone: '633-0130',
      email: 'bmobile_westmallES@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 07:00 PM"],"tue":["10:00 AM - 07:00 PM"],"wed":["10:00 AM - 07:00 PM"],"thu":["10:00 AM - 07:00 PM"],"fri":["10:00 AM - 07:00 PM"],"sat":["10:00 AM - 07:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '23',
      title: 'Cellmaster Limited',
      description: '',
      street:
        'Unit D107 Ext Block D, Level One, Trincity Mall , Trincity Central Road',
      city: 'Trincity',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6269678',
      lng: '-61.3541186',
      phone: '640-8315',
      email: 'bmobile_trincityES@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 07:00 PM"],"tue":["10:00 AM - 07:00 PM"],"wed":["10:00 AM - 07:00 PM"],"thu":["10:00 AM - 07:00 PM"],"fri":["10:00 AM - 07:00 PM"],"sat":["10:00 AM - 07:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '22',
      title: 'Cellmaster Limited',
      description: '',
      street: 'City Gate, Railway Building, South Quay',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6481799',
      lng: '-61.5078793',
      phone: '627-6323',
      email: 'citygate@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":"0","sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '20',
      title: 'Cellmaster Limited',
      description: '',
      street: '54 High Street',
      city: 'Siparia',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.0910494',
      lng: '-61.5252827',
      phone: '649-9557',
      email: 'siparia@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["08:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '17',
      title: 'Cellmaster Limited',
      description: '',
      street: 'Shop 16, Starlite Shopping Plaza, Diego Martin Main Road',
      city: 'Diego Martin',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6863385',
      lng: '-61.5538217',
      phone: '633-2101',
      email: 'starlite@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["10:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '18',
      title: 'Cellmaster Limited',
      description: '',
      street: 'Park Plaza, 59 Cor. Park & St. Vincent St',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6566032',
      lng: '-61.5123029',
      phone: '625-2084',
      email: 'parkstreet@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["08:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '19',
      title: 'Cellmaster Limited',
      description: '',
      street: 'Corner Cacique Street & High Street',
      city: 'Princes Town',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.2740544',
      lng: '-61.3743288',
      phone: '655-3369',
      email: 'ptown@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["08:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '21',
      title: 'Cellmaster Limited',
      description: '',
      street: '10-10A Devenish Street',
      city: 'Arima',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6393097',
      lng: '-61.2807392',
      phone: '664-0404',
      email: 'arima@cellmaster.com',
      website: 'www.cellmaster.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["08:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '26',
      title: 'Cells International Limited',
      description: '',
      street: 'Unit 13A Shoppes of Maraval',
      city: 'Maraval',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6817015',
      lng: '-61.5233794',
      phone: '622-7883',
      email: 'cellsinternational_ltd@yahoo.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 05:00 PM"],"tue":["10:00 AM - 05:00 PM"],"wed":["10:00 AM - 05:00 PM"],"thu":["10:00 AM - 05:00 PM"],"fri":["10:00 AM - 05:00 PM"],"sat":"0","sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '29',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Busy Corner Mall, 23 Main Road',
      city: 'Chaguanas',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.5143238',
      lng: '-61.409579',
      phone: '671-8530',
      email: 'cellularplanet.chaguanas@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 05:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '27',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Dial Corner Mall, #43 Broadway',
      city: 'Arima',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '42.3561111',
      lng: '-71.0608333',
      phone: '667-2146',
      email: 'cellularplanet.arima@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 02:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '41',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Upper Level, Gulf City Shopping Mall',
      city: 'La Romain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '34.0586592',
      lng: '-118.4190309',
      phone: '657-6816',
      email: 'cellularplanet.gulfcity@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '40',
      title: 'Cellular Planet Limited',
      description: '',
      street:
        'Shop # 5 , Ground Floor, El Socorro Shopping Village Ltd, Cor. 5th Street & El Socorro Road',
      city: 'San Juan',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '6.468665',
      lng: '-73.264041',
      phone: '675-0931',
      email: 'cellularplanet.sanjuan@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:30 AM - 06:00 PM"],"tue":["08:30 AM - 06:00 PM"],"wed":["08:30 AM - 06:00 PM"],"thu":["08:30 AM - 06:00 PM"],"fri":["08:30 AM - 06:00 PM"],"sat":["08:30 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '39',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Shop #243, Upper Level, The Falls at Westmall',
      city: 'Westmoorings',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6781651',
      lng: '-61.5536603',
      phone: '632-1323',
      email: 'cellularplanetwestmall@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '38',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Unit 1, Spence Plaza, Wilson Road',
      city: 'Scarborough, Tobago',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '11.1836165',
      lng: '-60.7376445',
      phone: '635-0504',
      email: 'cellularplanet.scarborough@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["08:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '37',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Store#1, Plaza Grande, Eastern Main Road',
      city: 'Sangre Grande',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.576298',
      lng: '-61.121788',
      phone: '691-3018',
      email: 'cellularplanet.sangregrande@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:30 AM - 05:00 PM"],"tue":["08:30 AM - 05:00 PM"],"wed":["08:30 AM - 05:00 PM"],"thu":["08:30 AM - 05:00 PM"],"fri":["08:30 AM - 05:00 PM"],"sat":["08:30 AM - 02:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '35',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Lowlands Mall, Lowlands',
      city: 'Tobago',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '11.1610467',
      lng: '-60.7795472',
      phone: '631-0356',
      email: 'cellularplanet.lowlandsmall@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '28',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Cameo House, #2 Broadway',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6603196',
      lng: '-61.5085625',
      phone: '627-7900',
      email: 'cellularplanet.broadway@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:30 PM"],"tue":["09:00 AM - 05:30 PM"],"wed":["09:00 AM - 05:30 PM"],"thu":["09:00 AM - 05:30 PM"],"fri":["09:00 AM - 05:30 PM"],"sat":["08:00 AM - 12:30 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '30',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Moonan Building, 97-98, Naparima Mayaro Road',
      city: 'Rio Claro',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.3059312',
      lng: '-61.1645257',
      phone: '644-2355',
      email: 'cellularplanet.rioclaro@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:30 AM - 05:00 PM"],"tue":["08:30 AM - 05:00 PM"],"wed":["08:30 AM - 05:00 PM"],"thu":["08:30 AM - 05:00 PM"],"fri":["08:30 AM - 05:00 PM"],"sat":["08:30 AM - 02:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '31',
      title: 'Cellular Planet Limited',
      description: '',
      street: '#4 Guayaguayare Main Road',
      city: 'Mayaro',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.2803437',
      lng: '-61.0296696',
      phone: '630-2355',
      email: 'cellularplanet.mayaro@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:30 AM - 05:00 PM"],"tue":["08:30 AM - 05:00 PM"],"wed":["08:30 AM - 05:00 PM"],"thu":["08:30 AM - 05:00 PM"],"fri":["08:30 AM - 05:00 PM"],"sat":["09:00 AM - 01:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '34',
      title: 'Cellular Planet Limited',
      description: '',
      street:
        'Unit 1.K14, Level 1 Long Circular Mall (Southern Entrance), 51-53, Long Circular Road',
      city: 'St. James',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6712686',
      lng: '-61.5294577',
      phone: '628-6687',
      email: 'cellularplanet.lcm@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '36',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Shop #45, Lot A, Lower Level Princes Town Mall, High Street',
      city: 'Princes Town',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.271347',
      lng: '-61.3766463',
      phone: '655-6194',
      email: 'ptownmallcp@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 05:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '33',
      title: 'Cellular Planet Limited',
      description: '',
      street: 'Uptown Excellent Mall, Corner Frederick and Park Street',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6566032',
      lng: '-61.5123029',
      phone: '623-9610',
      email: 'cellularplanet.excellent@gmail.com',
      website: 'www.cellular-planet.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["09:00 AM - 02:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '43',
      title: 'Colours in Motion',
      description: '',
      street: 'Upper Level, RPM Plaza, High Street',
      city: 'San Fernando',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.3015828',
      lng: '-61.4490453',
      phone: '653-4719',
      email: 'coloursinmotion@ymail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:30 AM - 05:00 PM"],"tue":["08:30 AM - 05:00 PM"],"wed":["08:30 AM - 05:00 PM"],"thu":["08:30 AM - 05:00 PM"],"fri":["08:30 AM - 05:00 PM"],"sat":["08:30 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '44',
      title: 'Colours in Motion',
      description: '',
      street: 'Shop D09A, Lower Level, Gulf City Shopping Mall',
      city: 'La Romain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '27.70556',
      lng: '-82.46194',
      phone: '653-7102',
      email: 'coloursinmotion@ymail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 07:00 PM"],"sun":["10:00 AM - 3:00 PM"]}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat, Sun',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '42',
      title: 'Colours in Motion',
      description: '',
      street: '8 Mucurapo Street',
      city: 'San Fernando',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.2781446',
      lng: '-61.4628303',
      phone: '652-3739',
      email: 'coloursinmotion@ymail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:30 AM - 05:00 PM"],"tue":["08:30 AM - 05:00 PM"],"wed":["08:30 AM - 05:00 PM"],"thu":["08:30 AM - 05:00 PM"],"fri":["08:30 AM - 05:00 PM"],"sat":["08:30 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '45',
      title: 'Craftman Shop Limited',
      description: '',
      street: 'Valpark Shopping Plaza, Morequito Ave ',
      city: 'Valsayn',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.633049',
      lng: '-61.4187642',
      phone: '662-0506',
      email: 'craftmanshoplimited@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 05:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '46',
      title: 'Galita Trading Limited',
      description: '',
      street: '#64 Independence Square',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6499327',
      lng: '-61.5108816',
      phone: '623-1802',
      email: 'galitaactivation@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 03:30 PM"],"tue":["09:00 AM - 03:30 PM"],"wed":["09:00 AM - 03:30 PM"],"thu":["09:00 AM - 03:30 PM"],"fri":["09:00 AM - 03:30 PM"],"sat":["09:30 AM - 02:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '47',
      title: 'Hellopost Limited',
      description: '',
      street: 'Unit#9 Ground Floor, Movie Towne Mall, Audrey Jeffers Highway',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6587565',
      lng: '-61.532674',
      phone: '627-4149',
      email: 'manager.mt@hellopost.co.tt',
      website: 'www.hellopost.co.tt',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:30 AM - 06:00 PM"],"tue":["10:30 AM - 06:00 PM"],"wed":["10:30 AM - 06:00 PM"],"thu":["10:30 AM - 06:00 PM"],"fri":["10:30 AM - 06:00 PM"],"sat":["10:30 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '48',
      title: 'IESL Technologies Limited',
      description: '',
      street:
        "Shop 37, Ground Level (West) Gov't Campus Plaza, Parkade, Cor. Queen & Richmond Streets",
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6511216',
      lng: '-61.5134212',
      phone: '623-8669',
      email: 'bmobileparkade@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 04:00 PM"],"tue":["08:00 AM - 04:00 PM"],"wed":["08:00 AM - 04:00 PM"],"thu":["08:00 AM - 04:00 PM"],"fri":["08:00 AM - 04:00 PM"],"sat":["09:00 AM - 01:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '49',
      title: 'Jo Stal Enterprises Limited',
      description: '',
      street: '700, Munroe Road',
      city: 'Cunupia',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.5665478',
      lng: '-61.4148409',
      phone: '693-1800',
      email: 'jostal5@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 05:00 PM"],"tue":["10:00 AM - 05:00 PM"],"wed":["10:00 AM - 05:00 PM"],"thu":["10:00 AM - 05:00 PM"],"fri":["10:00 AM - 05:00 PM"],"sat":["10:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '50',
      title: 'Mobile Max Limited',
      description: '',
      street: '74 Aranguez Main Road',
      city: 'Aranguez',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6434425',
      lng: '-61.444544',
      phone: '674-3535',
      email: 'mobilemaxlimited@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["10:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '51',
      title: 'Mobility Biz Solutions and Services Limited',
      description: '',
      street: 'Cor. 2nd Street and Saddle Road',
      city: 'San Juan',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6632452',
      lng: '-61.4500192',
      phone: '674-7079',
      email: 'mbssl2003@gmail.com',
      website: 'www.mobilitytt.com',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 06:00 PM"],"tue":["08:00 AM - 06:00 PM"],"wed":["08:00 AM - 06:00 PM"],"thu":["08:00 AM - 06:00 PM"],"fri":["08:00 AM - 06:00 PM"],"sat":["08:00 AM - 04:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '53',
      title: 'Nova Glen Corporation Limited',
      description: '',
      street: '#161 Tragarete Road',
      city: 'Port of Spain',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.667049',
      lng: '-61.5251274',
      phone: '628-6681',
      email: 'novaglen1@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 05:00 PM"],"tue":["10:00 AM - 05:00 PM"],"wed":["10:00 AM - 05:00 PM"],"thu":["10:00 AM - 05:00 PM"],"fri":["10:00 AM - 05:00 PM"],"sat":["10:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '54',
      title: 'Nova Quantum Limited',
      description: '',
      street: 'Duty Free Kiosk, Piarco International Airport',
      city: 'Piarco',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.5976964',
      lng: '-61.339527',
      phone: '669-8853',
      email: 'novaquantum1piarco@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["04:30 PM - 12:00 AM"],"tue":["04:30 PM - 12:00 AM"],"wed":["04:30 PM - 12:00 AM"],"thu":["04:30 PM - 12:00 AM"],"fri":["04:30 PM - 12:00 AM"],"sat":["04:30 PM - 12:00 AM"],"sun":["04:30 PM - 12:00 AM"]}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat, Sun',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '55',
      title: 'Rale Marketing Limited',
      description: '',
      street: 'Carlton Centre Link Mall, High Street',
      city: 'San Fernando',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.2820305',
      lng: '-61.4633915',
      phone: '771-7335/769-3418',
      email: 'tsttrale@yahoo.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:45 AM - 04:30 PM"],"tue":["08:45 AM - 04:30 PM"],"wed":["08:45 AM - 04:30 PM"],"thu":["08:45 AM - 04:30 PM"],"fri":["08:45 AM - 04:30 PM"],"sat":["08:45 AM - 03:30 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '56',
      title: 'Rollocks Car Rental Limited',
      description: '',
      street: 'Store Bay Local Road, Bon Accord',
      city: 'Canaan, Tobago',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '11.1518288',
      lng: '-60.8198891',
      phone: '631-1274',
      email: 'mobilehut_1@hotmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["09:00 AM - 01:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '58',
      title: 'The Distribution Company Limited',
      description: '',
      street: '57 Cipero Street, Gooding Village',
      city: 'San Fernando',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.2696313',
      lng: '-61.4597713',
      phone: '657-3641',
      email: 'trinicel@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["9:00 AM - 03:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '59',
      title: 'The Distribution Company Limited',
      description: '',
      street: 'Building 8, Shop 3, Grand Bazaar, C.R.H. & Uriah Butler Highway',
      city: 'Valsayn',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6311201',
      lng: '-61.427268',
      phone: '663-1200',
      email: 'trinicelgb@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 06:00 PM"],"tue":["10:00 AM - 06:00 PM"],"wed":["10:00 AM - 06:00 PM"],"thu":["10:00 AM - 06:00 PM"],"fri":["10:00 AM - 06:00 PM"],"sat":["10:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '60',
      title: 'The Distribution Company Limited',
      description: '',
      street: 'Gasparillo Mall, Bonne Aventure Road',
      city: 'Gasparillo',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.3153408',
      lng: '-61.4287481',
      phone: '650-3846',
      email: 'trinicelgasparillo@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 06:00 PM"],"tue":["09:00 AM - 06:00 PM"],"wed":["09:00 AM - 06:00 PM"],"thu":["09:00 AM - 06:00 PM"],"fri":["09:00 AM - 06:00 PM"],"sat":["09:00 AM - 06:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '61',
      title: 'Toxic Boutique Limited',
      description: '',
      street: 'Corner Wellington Road and SS Erin Road',
      city: 'Debe',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.211791',
      lng: '-61.4528166',
      phone: '647-1125',
      email: 'nijahtech@gmail.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 05:00 PM"],"tue":["09:00 AM - 05:00 PM"],"wed":["09:00 AM - 05:00 PM"],"thu":["09:00 AM - 05:00 PM"],"fri":["09:00 AM - 05:00 PM"],"sat":["9:00 AM - 03:30 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '62',
      title: 'Ultimate Cells',
      description: '',
      street: 'Shop #10A Upper Level, Trincity Mall, Trincity Central Road',
      city: 'Trincity',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.6269678',
      lng: '-61.3541186',
      phone: '640-1407',
      email: 'ultimatecells@yahoo.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["10:00 AM - 08:00 PM"],"tue":["10:00 AM - 08:00 PM"],"wed":["10:00 AM - 08:00 PM"],"thu":["10:00 AM - 08:00 PM"],"fri":["10:00 AM - 08:00 PM"],"sat":["10:00 AM - 08:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: '',
      mobile_bill_payment_card_only: 'Yes',
      res_bill_payment_cash_and_card: '',
      res_bill_payment_card_only: 'Yes',
      amplia_bill_pay_cash_and_card: '',
      amplia_bill_pay_card_only: 'Yes',
      amplia_sign_up: 'Yes',
    },
    {
      id: '63',
      title: "Wayne's Electronics Limited",
      description: '',
      street: '80 Main Road',
      city: 'Point Fortin',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.1732898',
      lng: '-61.6810582',
      phone: '648-2188',
      email: 'waynesbmobile@yahoo.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["08:00 AM - 05:00 PM"],"tue":["08:00 AM - 05:00 PM"],"wed":["08:00 AM - 05:00 PM"],"thu":["08:00 AM - 05:00 PM"],"fri":["08:00 AM - 05:00 PM"],"sat":["08:00 AM - 05:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
    {
      id: '64',
      title: 'Zee Cellular Shop',
      description: '',
      street: 'Shop #4, Centre Pointe Mall, Ramsaran Street',
      city: 'Chaguanas',
      state: '',
      postal_code: '',
      country: 'United States',
      lat: '10.5119411',
      lng: '-61.4105874',
      phone: '671-3607',
      email: 'zeecellular@yahoo.com',
      website: '',
      logo_id: '0',
      path: null,
      marker_id: '0',
      description_2: '',
      open_hours:
        '{"mon":["09:00 AM - 04:00 PM"],"tue":["09:00 AM - 04:00 PM"],"wed":["09:00 AM - 04:00 PM"],"thu":["09:00 AM - 04:00 PM"],"fri":["09:00 AM - 04:00 PM"],"sat":["09:00 AM - 04:00 PM"],"sun":"0"}',
      ordr: '0',
      brand: '',
      categories: '19',
      days_str: 'Mon, Tues, Wed, Thur, Fri, Sat',
      new_sim_purchase: 'Yes',
      handset_purchase: 'Yes',
      postpaid_sign_up: 'Yes',
      prepaid_sign_up: 'Yes',
      wireless_internet_service_sign_up: 'Yes',
      residential_service: 'Yes',
      vigilance_security_service_sign_up: 'Yes',
      mobile_bill_payment_cash_and_card: 'Yes',
      mobile_bill_payment_card_only: '',
      res_bill_payment_cash_and_card: 'Yes',
      res_bill_payment_card_only: '',
      amplia_bill_pay_cash_and_card: 'Yes',
      amplia_bill_pay_card_only: '',
      amplia_sign_up: 'Yes',
    },
  ];
  